# Generated by Django 4.2.8 on 2023-12-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
